### ISSUE TITLE
progression bar

### ISSUE THREAD

**Issue by pedrocr83** [BioData-PT/Biome-Shiny#5]
If your dataset is big enough some metrics and graphs are gonna take some time.. i suggest a progression bar of sorts

**Comment by Klink5D** [comment]
Began adding progression bars, though it's still basic and mostly just tell the user that progress is happening. I'd like to improve the bars' progress tracking before closing this issue, but it's a start.

**Comment by Klink5D** [comment]
Loading bars should provide more information now
